const CartActionTypes = {
	TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
	ADD_ITEM: 'ADD_ITEM',
	REMOVE_ITEM: 'REMOVE_ITEM',
	INCREASE_ITEM_QUATITY: 'INCREASE_ITEM_QUATITY',
	DECREASE_ITEM_QUATITY: 'DECREASE_ITEM_QUATITY',
};
export default CartActionTypes;
